import type { ChatMessage } from "./types";

export interface CompactionResult {
	messages: ChatMessage[];
	compacted: boolean;
	removedMessages: number;
	estimatedTokens: number;
	summary?: string;
}

export function estimateMessageTokens(messages: ChatMessage[]): number {
	return Math.ceil(messages.reduce((total, message) => total + message.content.length, 0) / 4);
}

/** Keep the latest exchange intact and replace older transcript content with a local summary. */
export function compactMessages(messages: ChatMessage[], maxTokens = 12_000): CompactionResult {
	const currentTokens = estimateMessageTokens(messages);
	if (currentTokens <= maxTokens) {
		return { messages, compacted: false, removedMessages: 0, estimatedTokens: currentTokens };
	}

	const system = messages.filter((message) => message.role === "system");
	const conversation = messages.filter((message) => message.role !== "system");
	const keepCount = Math.min(8, Math.max(2, conversation.length - 1));
	const kept = conversation.slice(-keepCount);
	const removed = conversation.slice(0, Math.max(0, conversation.length - keepCount));
	const summary = removed
		.map((message) => `${message.role}: ${message.content.replace(/\s+/g, " ").trim().slice(0, 700)}`)
		.join("\n");
	const summaryMessage: ChatMessage = {
		role: "system",
		content: `Conversation summary generated by Ogent. Preserve these goals, decisions, and facts:\n${summary.slice(0, 12_000)}`,
	};
	const compactedMessages = [...system, summaryMessage, ...kept];
	return {
		messages: compactedMessages,
		compacted: true,
		removedMessages: removed.length,
		estimatedTokens: estimateMessageTokens(compactedMessages),
		summary,
	};
}
